import {describe,expect,it} from 'vitest';
import {alexDraft,assign,cardTargets,computerAction,discardCard,drawCard,endRound,forecast,hexDistance,invest,newMonopoly,nextPhase,parlours,passDraft,pick,playCard,propertyCost,roomCount,score,shopStats,spin,staff,team,tacticalMove,tacticQuote,type Monopoly} from '../simple/monopoly';
function drafted(seed=.37){let g=newMonopoly(seed);let guard=0;while(g.phase==='pick'){if(g.draftTurn==='alex')g=alexDraft(g);else{const i=staff.findIndex((b,j)=>!g.workers[j]&&b.price<=g.cash.you);g=i<0?passDraft(g):pick(g,i);}if(++guard>10)throw Error('Draft did not finish');}return g;}
function ready(seed=.37){let g=nextPhase(drafted(seed));const shops=g.shops.flatMap((s,i)=>s==='you'?[i]:[]);for(const [j,i]of team(g,'you').entries())g=assign(g,i,shops[j%shops.length]);return g;}
function investment(){return drawCard(nextPhase(spin(nextPhase(ready()),3,.99)),7);}
describe('Massage Monopoly v4',()=>{
 it('has twelve adult balanced cards with bell-shaped trait distributions',()=>{expect(staff).toHaveLength(12);expect(new Set(staff.map(s=>s.ethnicity)).size).toBe(6);expect(Math.min(...staff.map(s=>s.age))).toBeGreaterThanOrEqual(23);for(const trait of ['friendliness','aggression','sneakiness'] as const)expect([1,2,3,4,5].map(n=>staff.filter(s=>s[trait]===n).length)).toEqual([1,3,4,3,1]);expect(staff.every(s=>s.tagline&&s.strength&&s.weakness)).toBe(true);});
 it('alternates paid picks and allows one star to consume the whole budget',()=>{const start=newMonopoly(.2);const n=pick(start,3);expect(n.cash.you).toBe(0);expect(n.workers[3]).toBe('you');expect(n.draftTurn).toBe('alex');expect(pick(n,0)).toBe(n);expect(n.draftDone.you).toBe(true);const a=alexDraft(n);expect(a.cash.alex).toBeLessThan(1800);const done=drafted();expect(done.phase).toBe('reveal');expect(team(done,'you').length).toBeLessThanOrEqual(3);expect(team(done,'alex').length).toBeLessThanOrEqual(3);expect(done.cash.you).toBeGreaterThanOrEqual(0);});
 it('reveals a randomized equal-value three-shop start on a radius-two honeycomb',()=>{expect(parlours).toHaveLength(19);expect(parlours.every(p=>Math.max(Math.abs(p.q),Math.abs(p.r),Math.abs(p.q+p.r))<=2)).toBe(true);const a=newMonopoly(.1),b=newMonopoly(.7);expect(a.shops).not.toEqual(b.shops);expect(a.shops.filter(s=>s==='you')).toHaveLength(3);expect(a.shops.filter(s=>s==='alex')).toHaveLength(3);expect(score(a,'you')).toBe(score(a,'alex'));expect(hexDistance(0,1)).toBe(1);});
 it('enforces rooms and ownership on every drag/drop assignment',()=>{let g=ready();const members=team(g,'you'),shop=g.shops.findIndex(s=>s==='you'),rival=g.shops.findIndex(s=>s==='alex');g=assign(g,members[0],shop);g=assign(g,members[1],shop);if(members[2]!==undefined)expect(assign(g,members[2],shop)).toBe(g);expect(assign(g,members[0],rival)).toBe(g);expect(assign(g,99,shop)).toBe(g);expect(forecast(g,'you').costs).toBeGreaterThan(0);});
 it('patrols, aggression and sneakiness affect risk, with a forced asset loss on night two',()=>{const g=ready(),shop=g.assignments[team(g,'you')[0]]!;expect(shopStats({...g,patrols:[shop,shop]},shop).risk).toBeGreaterThanOrEqual(shopStats(g,shop).risk);const before=team(g,'you').length+g.shops.filter(s=>s==='you').length;const n=spin({...g,phase:'spin',round:2},3,.99);expect(n.police).toBe(true);expect(n.raidEvents.some(e=>e.side==='you')).toBe(true);expect(team(n,'you').length+n.shops.filter(s=>s==='you').length).toBe(before-1);expect(n.reward.you).toBe(n.gross.you-n.costs.you-n.losses.you);expect(n.shops.filter(s=>s==='you').length).toBeGreaterThanOrEqual(1);expect(spin(n,3)).toBe(n);});
 it('Tip-Off prevents contract/property losses for the protected side',()=>{const g=ready();const n=spin({...g,phase:'spin',round:2,shield:{you:true,alex:false}},3,.99);expect(n.losses.you).toBe(0);expect(n.raidEvents.some(e=>e.side==='you')).toBe(false);expect(team(n,'you')).toEqual(team(g,'you'));});
 it('cards immediately alter the rival’s investment options and patrol exposure',()=>{const g=investment(),shop=g.shops.findIndex(s=>s==='alex');const blocked=playCard({...g,card:3},shop);expect(blocked.blocked.alex).toBe(true);expect(blocked.cash.alex).toBe(Math.max(0,g.cash.alex-250));expect(playCard(blocked,shop)).toBe(blocked);const hot=playCard({...g,card:4},shop);expect(hot.patrols[0]).toBe(shop);expect(hot.heat[shop]).toBe(2);const closed=playCard({...g,card:5},shop);expect(closed.shops[shop]).toBeNull();expect(closed.assignments.includes(shop)).toBe(false);});
 it('cards can poach, discount, train, and require legal targets',()=>{const g=investment();const worker=team(g,'alex')[0],poached=playCard({...g,card:6},worker);expect(poached.workers[worker]).toBe('you');expect(poached.hires.you).toBe(1);expect(playCard({...g,card:6},99)).toEqual({...g,card:6});const discounted=playCard({...g,card:0});expect(propertyCost(discounted,0)).toBe(650);const trained=invest({...g,cash:{...g.cash,you:1000}},'train',team(g,'you')[0]);expect(trained.levels[team(g,'you')[0]]).toBe(1);expect(endRound(g)).toBe(g);expect(endRound(discardCard(g)).phase).toBe('computer');});
 it('protects the last shop and allows selling another to rebuild staff',()=>{const g=investment(),own=g.shops.findIndex(s=>s==='you');const sold=invest(g,'sell',own);expect(sold.cash.you).toBe(g.cash.you+850);expect(sold.shops[own]).toBeNull();const only:Monopoly={...g,shops:g.shops.map((o,i)=>o==='alex'&&i!==g.shops.findIndex(s=>s==='alex')?null:o)};expect(cardTargets(only,5)).toHaveLength(0);});
 it('runs a full ten-night game with recruitment limits and legal computer placement',()=>{let g=ready();for(let night=1;night<=10;night++){g=spin(nextPhase(g),3,.99);g=drawCard(nextPhase(g),7);g=endRound(playCard(g));let guard=0;while(g.phase==='computer'){g=computerAction(g,7);expect(g.cash.alex).toBeGreaterThanOrEqual(0);expect(g.hires.alex).toBeLessThanOrEqual(1);expect(g.moves.alex).toBeLessThanOrEqual(2);if(++guard>30)throw Error('Computer turn stuck');}for(let s=0;s<parlours.length;s++)expect(g.assignments.filter(a=>a===s).length).toBeLessThanOrEqual(2);if(g.phase==='assign'){for(const i of team(g,'you')){const shop=g.shops.findIndex((s,j)=>s==='you'&&g.assignments.filter(a=>a===j).length<2);if(shop>=0)g=assign(g,i,shop);}}}expect(g.phase).toBe('over');expect(g.round).toBe(10);expect(roomCount(g,'you')).toBeGreaterThan(0);});
});

describe('tactical staff orders',()=>{
 it('supports adjacent pressure, patrol lures, and two orders per night',()=>{
  let g=ready();const worker=team(g,'you')[0],base=g.assignments[worker]!;
  const adjacent=parlours.findIndex((_,i)=>hexDistance(base,i)===1);
  g={...g,cash:{you:2000,alex:2000},shops:g.shops.map((o,i)=>i===adjacent?'alex':o)};
  const quote=tacticQuote(g,worker,adjacent,'pressure');expect(quote.legal).toBe(true);
  const pressed=tacticalMove(g,worker,adjacent,'pressure');expect(pressed.cash.alex).toBe(2000-staff[worker].aggression*45);expect(pressed.heat[base]).toBe(1);
  const lured=tacticalMove(pressed,worker,adjacent,'lure');expect(lured.patrols).toContain(adjacent);expect(lured.tacticsUsed).toBe(2);expect(tacticalMove(lured,worker,base,'promote')).toBe(lured);
 });
 it('rewards connected claims and shows the cost before commitment',()=>{
  let g=ready();const worker=team(g,'you')[0],base=g.assignments[worker]!;
  const target=parlours.findIndex((_,i)=>hexDistance(base,i)===1);
  g={...g,cash:{...g.cash,you:2000},shops:g.shops.map((o,i)=>i===target?null:o)};
  const quote=tacticQuote(g,worker,target,'claim');expect(quote.cost).toBeLessThan(1000);
  const claimed=tacticalMove(g,worker,target,'claim');expect(claimed.shops[target]).toBe('you');expect(claimed.cash.you).toBe(2000-quote.cost);
 });
});
