import { TurnFlow } from './TurnFlow';
import { MonopolyBoard } from './MonopolyBoard';
import { useEffect,useState } from 'react';
import { Portrait } from '@/simple/Portrait';
import { staff } from '@/simple/monopoly';
import { enterTurn,storyBeat,draftPool,openDraft,recruitDraft,finishDraft,beats,chooseStory,continueStory,freshStory,type StoryState } from './story';
import './demo.css';
const money=(n:number)=>`${n<0?'−':''}$${Math.abs(n).toLocaleString()}`;
const key='massage-monopoly-story-v4-full-turn';
function load():StoryState{try{const g=JSON.parse(localStorage.getItem(key)??'null');if(g?.version===1&&['intro','draft','reveal','turn','choice','result','ending'].includes(g.screen)&&g.beat>=0&&g.beat<beats.length&&Array.isArray(g.history)&&Array.isArray(g.crew)&&Array.isArray(g.shops)&&Number.isFinite(g.cash)&&Number.isFinite(g.alexCash))return g;}catch{/* Start fresh. */}return freshStory();}
export function DemoApp(){
 const[g,set]=useState(load),[spinning,setSpinning]=useState(false),[pending,setPending]=useState<number|null>(null),[rain,setRain]=useState(false),[rules,setRules]=useState(false),[reveal,setReveal]=useState(false),[preview,setPreview]=useState<number|null>(null),[locked,setLocked]=useState<number|null>(null);
 useEffect(()=>{try{localStorage.setItem(key,JSON.stringify(g));}catch{/* Play without storage. */}},[g]);
 useEffect(()=>{if(!spinning||pending===null)return;const t=setTimeout(()=>{set(current=>chooseStory(current,pending));setSpinning(false);setPending(null);setRain(true);},1000);return()=>clearTimeout(t);},[spinning,pending]);
 useEffect(()=>{if(!rain)return;const t=setTimeout(()=>setRain(false),2700);return()=>clearTimeout(t);},[rain]);
 useEffect(()=>{if(locked===null)return;const t=setTimeout(()=>setLocked(null),1800);return()=>clearTimeout(t);},[locked]);
 useEffect(()=>{if(!reveal)return;const t=setTimeout(()=>setReveal(false),1600);return()=>clearTimeout(t);},[reveal]);
 const b=storyBeat(g),choice=g.lastChoice===null?null:b.choices[g.lastChoice],police=(g.screen==='choice'||(g.screen==='turn'&&g.turnStage==='placement'))&&!!b.event;
 const select=(i:number)=>{setPending(i);setSpinning(true);};
 const advance=()=>{setRain(false);setPreview(null);set(continueStory);};
 const board=<section className="story-board" aria-label="Strategic city board">
 <div className="story-map-heading"><div><span className="story-eyebrow">THE MONEY MILE · LIVE BOARD</span><h2>Your position. His weak point.</h2></div><div className="story-map-legend"><span>● YOU</span><span>● ALEX</span><span>◇ AVAILABLE</span></div></div>
 <MonopolyBoard game={g}/>
 <div className="story-board-readout" aria-live="polite"><span>{g.screen==='result'?'MOVE RESOLVED':preview!==null?'PREVIEW THIS MOVE':'READ THE BOARD'}</span><p>{g.screen==='result'?choice!.result:preview!==null?b.choices[preview].hint:g.beat<3?'You own Golden Lotus. Alex has hotel traffic; the waterfront is an opening.':g.closed?'Golden Lotus is closed. Your waterfront keeps you in the fight.':g.beat>=6?'Alex relies on Imperial House. Protect your income while attacking his dependency.':'Your team has a waterfront foothold. Build that advantage before police attention catches up.'}</p></div></section>;

 return <main className="story-app"><header className="story-header"><div><span className="story-eyebrow">A PLAYABLE RIVALRY</span><h1>Massage Monopoly<span>.</span></h1></div><div><span className="story-demo-badge">STORY DEMO</span><button onClick={()=>setRules(!rules)}>{rules?'Close guide':'About this demo'}</button></div></header>
 {rules&&<section className="story-guide"><h2>The first rivalry</h2><p>This is a deliberately choreographed pitch demo. Ten turns introduce the mechanics through confidence, threat, discovery, setbacks and a comeback. Outcomes are authored, not random: the displayed cash changes are guaranteed. Alex’s remarks and events reveal one idea at a time. Choices affect your cash, attention, crew and properties; the demo is designed to end in a player victory.</p><p>Net values include the costs named on each option. The opening deals you Siriporn, Golden Lotus, $1,800 for team selection and $600 operating cash. Pick your team, reveal the board, then face ten escalating decisions. Each turn runs through placement, night payout, strategy draw and play, cash allocation and ending the turn. All money is fictional. Progress saves locally. Restart to try the other decisions.</p></section>}
 {g.screen==='intro'?<section className="story-intro"><div className="story-intro-copy"><span className="story-eyebrow">YOUR MAMASAN. YOUR SHOP. YOUR TEAM.</span><h2>This is yours.<br/>Make it count.</h2><p>Siriporn runs Golden Lotus. The shop is yours. Now choose the team who will work your first night. Alex picks from the same pool.</p><button className="story-primary" onClick={()=>{set(openDraft);}}>Pick your team →</button></div><div className="story-opening-card"><Portrait index={11} name="Siriporn"/><div><span>YOUR MAMASAN</span><h3>Siriporn · 45</h3><strong>The boss who keeps your team together.</strong><p>Already assigned to Golden Lotus.</p></div></div><div className="story-rival intro-rival"><div className="story-alex-face">A<span>THE SHARK</span></div><div><b>ALEX</b><blockquote>“One shop. One operator. Try to keep them.”</blockquote></div></div></section>:g.screen==='draft'?<section className="story-draft"><span className="story-eyebrow">SIRIPORN’S GOLDEN LOTUS · CAPTAIN’S PICKS</span><h2>Build your first team.</h2><p>You pick. Alex picks. Up to three staff each. Your $1,800 recruitment budget is separate from your $600 operating cash.</p><div className="story-draft-status"><strong>Your budget: {money(g.draftBudget??0)}</strong><span>Your team: {g.crew.length}/3 · Alex: {g.alexCrew?.length??0}/3</span></div><div className="story-draft-cards">{draftPool.map(i=>{const person=staff[i],yours=g.crew.includes(i),enemy=g.alexCrew?.includes(i),disabled=yours||enemy||g.crew.length>=3||person.price>(g.draftBudget??0);return <button className={yours?'draft-owned':enemy?'draft-enemy':''} key={i} disabled={disabled} onClick={()=>{set(current=>recruitDraft(current,i));setLocked(i);}}><Portrait index={i} name={person.name}/><h3>{person.name}</h3><strong>{person.tagline}</strong><p>{person.strength}</p><small>{person.weakness}</small><b>{yours?'♥ LOCKED IN · YOUR TEAM':enemy?'ALEX TOOK THIS PICK':money(person.price)+' · RECRUIT'}</b></button>;})}</div><div className="story-draft-status"><span>Alex’s team: {(g.alexCrew??[]).map(i=>staff[i].name).join(', ')||'Waiting for your first pick'}</span><button className="story-primary" disabled={!g.crew.length} onClick={()=>{set(finishDraft);setReveal(true);}}>Lock team & reveal the board →</button></div></section>:<><section className="story-score"><div><span>♛ YOUR CASH</span><strong>{money(g.cash)}</strong><small>{g.crew.length} staff · {g.shops.length} properties · {g.heat<=2?'Discreet':g.heat<=5?'Getting noticed':'Police attention rising'}</small></div><div><span>♜ ALEX’S CASH</span><strong>{money(g.alexCash)}</strong><small>{g.cash>=g.alexCash?'You lead. He knows it.':'He leads. There’s an opening.'}</small></div><div><span>YOUR STORY</span><strong>{g.screen==='reveal'?'OPENING':g.screen==='ending'?'FINALE':`${g.beat+1} / ${beats.length}`}</strong><small>{g.screen==='ending'?'From first shop to comeback':'One decision at a time'}</small></div></section>
 {g.screen==='reveal'?<section className="story-act"><span className="story-eyebrow">THE CITY IS REVEALED</span><h2>Your team. Your foothold. His advantage.</h2><p>Pink is yours. Blue is Alex. Golden Lotus is your starting shop. Allocate your drafted team to Golden Lotus, then spin your first night.</p><div className={`story-scene ${reveal?'revealing':''}`}>{board}{reveal&&<><div className="story-curtain left"/><div className="story-curtain right"/></>}</div><button className="story-primary story-reveal-next" onClick={()=>set(enterTurn)}>Allocate your team →</button></section>:g.screen==='turn'?<TurnFlow game={g} set={set} board={board}/>:g.screen==='ending'?<section className="story-ending"><span className="story-eyebrow">YOU TURNED THE TABLES</span><h2>The Mile is yours.</h2><p>You began with one shop and one question. You learned from Alex, survived the police, and used his own weaknesses against him.</p><div className="story-final-score"><b>{money(g.cash)}<small>YOUR FINAL CASH</small></b><b>{money(g.alexCash)}<small>ALEX’S FINAL CASH</small></b></div><div className="story-rival"><div className="story-alex-face defeated">A<span>BEATEN</span></div><blockquote>“Lucky card. Convenient memory of everything before it.”</blockquote></div><h3>Your comeback</h3><div className="story-timeline">{g.history.map(h=><div key={h.beat}><span>{h.beat+1}</span><b>{beats[h.beat].choices[h.choice].label}</b><small>{money(h.cash)} net</small></div>)}</div><button className="story-primary" onClick={()=>set(freshStory())}>Play the other hand →</button></section>:<>
 <section className="story-rival"><div className={`story-alex-face ${g.beat>=6?'worried':''}`}>A<span>{g.beat>=6?'UNDER PRESSURE':'THE SHARK'}</span></div><div><b>ALEX</b><blockquote>“{g.screen==='result'?choice!.reaction:b.alex}”</blockquote></div></section>
 {g.screen==='choice'&&<section className="story-act"><span className="story-eyebrow">{g.beat===0?'YOUR FIRST NIGHT':`CHAPTER ${g.beat+1}`}</span><h2>{b.title}</h2><p>{b.prompt}</p>{b.event&&<div className={`story-event ${g.beat===5?'strike':'warning'}`} role="status"><b>🚨 {b.event.title}</b><p>{b.event.text}</p></div>}<div className={`story-scene ${reveal?'revealing':''}`}>{board}{reveal&&<><div className="story-curtain left"/><div className="story-curtain right"/></>}</div><div className="story-choices">{b.choices.map((c,i)=><button key={c.label} disabled={spinning} onMouseEnter={()=>setPreview(i)} onFocus={()=>setPreview(i)} onClick={()=>select(i)}><span>0{i+1}</span><strong>{c.label}</strong><small>{c.hint}</small><b>{spinning&&pending===i?'THE NIGHT IS UNFOLDING…':'MAKE THIS MOVE →'}</b></button>)}</div></section>}
 {g.screen==='result'&&choice&&<>{board}<section className="story-result" aria-live="polite"><span className="story-eyebrow">{choice.label}</span><h2>{g.beat===2?'A lesson worth remembering.':g.beat===6?'He felt that.':g.beat===7?'You saw the cost coming.':'Your move had consequences.'}</h2><strong className="story-payout">{money(choice.cash)}</strong><p>{choice.result}</p><div className="story-lesson"><span>WHAT YOU JUST LEARNED</span><b>{choice.lesson}</b></div><button className="story-primary" onClick={advance}>{g.beat===beats.length-1?'See the finish →':'What happens next? →'}</button></section></>}
 </>}
 </>}
 <footer className="story-footer"><span>Guided story demo · authored outcomes · auto-saved</span><button disabled={spinning} onClick={()=>{if(confirm('Restart the story demo?')){set(freshStory());setRain(false);}}}>Restart</button></footer>
 {locked!==null&&<div className="story-lock-celebration" aria-live="polite"><strong>{staff[locked].name} · LOCKED IN</strong><span>♥ ✦ ♥ ✦ ♥</span><small>Your move. Alex responds.</small></div>}
 {rain&&<div className="story-cash-rain" aria-hidden="true">{Array.from({length:24},(_,i)=><span key={i} style={{left:`${i*37%100}%`,animationDelay:`${i%6*.1}s`}}>💵</span>)}</div>}
 {police&&<div className={`story-police-edge ${g.beat===5?'dramatic':''}`} aria-hidden="true"/>}
 </main>;
}
