import { useEffect,useState,type Dispatch,type SetStateAction,type ReactNode } from 'react';
import { staff } from '@/simple/monopoly';
import { Portrait } from '@/simple/Portrait';
import { allocateTurnCash,drawTurnCard,endTurn,lockPlacement,placeWorker,playTurnCard,resolveTurnNight,storyBeat,turnCards,type StoryState } from './story';
const cash=(n:number)=>'$'+n.toLocaleString();
export function TurnFlow({game:g,set,board}:{game:StoryState;set:Dispatch<SetStateAction<StoryState>>;board:ReactNode}){
 const [selected,pick]=useState<number|null>(null),[spin,spinning]=useState<number|null>(null),[rain,setRain]=useState(false);
 useEffect(()=>{if(spin===null)return;const t=setTimeout(()=>{set(x=>resolveTurnNight(x,spin));spinning(null);setRain(true);},1400);return()=>clearTimeout(t);},[spin,set]);
 useEffect(()=>{if(!rain)return;const t=setTimeout(()=>setRain(false),2400);return()=>clearTimeout(t);},[rain]);
 const b=storyBeat(g),stage=g.turnStage??'placement';
 const steps=['placement','night','carddraw','cardplay','cash','end'];
 return <section className="full-turn"><nav className="turn-steps" aria-label="Turn progress">{['Assign team','Spin night','Draw card','Play card','Allocate cash','End turn'].map((label,i)=><span className={stage===steps[i]?'current':''} key={label}>{i+1} · {label}</span>)}</nav><h2>{b.title}</h2><p>{b.prompt}</p>{b.event&&<div className="story-event"><b>🚨 {b.event.title}</b><p>{b.event.text}</p></div>}{board}
 {stage==='placement'&&<div className="turn-panel"><h3>Allocate your team to your shops</h3><p>Select a worker, then a shop below—or drag their card onto a shop. Waterfront placement adds $25 per worker tonight. Closed shops cannot earn.</p><div className="turn-workers">{g.crew.map(i=><button draggable onDragStart={e=>e.dataTransfer.setData('text/plain',String(i))} className={selected===i?'selected':''} onClick={()=>pick(i)} key={i}><Portrait index={i} name={staff[i].name} small/><strong>{staff[i].name}</strong><small>{g.assignments?.[i]??'UNASSIGNED'}</small></button>)}</div><div className="turn-destinations">{g.shops.map(shop=><button key={shop} disabled={g.closed&&shop==='Golden Lotus'} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData('text/plain');if(id)set(x=>placeWorker(x,Number(id),shop));}} onClick={()=>{if(selected!==null)set(x=>placeWorker(x,selected,shop));}}><b>🏮 {shop}</b><small>{g.closed&&shop==='Golden Lotus'?'POLICE CLOSURE':shop==='Golden Lotus'?'Home base · baseline income':'Tourist bookings · +$25 per assigned worker'}</small><span>{g.crew.filter(i=>g.assignments?.[i]===shop).map(i=>staff[i].name).join(', ')||'Drop staff here'}</span></button>)}</div><button className="story-primary" disabled={!g.crew.every(i=>g.assignments?.[i])} onClick={()=>set(lockPlacement)}>Lock placements →</button></div>}
 {stage==='night'&&<div className="turn-panel"><h3>Spin for the night</h3><p>Choose this chapter’s approach. The story demo engineers the result; your placement and training add real bonuses.</p><div className="story-choices">{b.choices.map((c,i)=><button key={i} disabled={spin!==null} onClick={()=>spinning(i)}><strong>{c.label}</strong><small>{c.hint}</small><b>{spin===i?'🎰 SPINNING…':'🎰 SPIN THE NIGHT'}</b></button>)}</div></div>}
 {stage==='carddraw'&&<div className="turn-panel"><h3>💵 Night complete</h3><strong className="story-payout">{cash(b.choices[g.lastChoice??0].cash+(g.nightBonus??0))}</strong><p>{g.turnNote}</p><p>Placement and training bonus: {cash(g.nightBonus??0)}. Alex earned {cash(Math.max(0,b.choices[g.lastChoice??0].alex))}{b.choices[g.lastChoice??0].alex<0?' (his losses are reflected above)':''}.</p><blockquote>Alex: “{b.choices[g.lastChoice??0].reaction}”</blockquote><button className="story-primary" onClick={()=>set(drawTurnCard)}>Draw your strategy card →</button></div>}
 {stage==='cardplay'&&<div className="turn-panel turn-strategy"><span className="story-eyebrow">YOUR STRATEGY CARD</span><h3>🃏 {turnCards[g.drawnCard??0].name}</h3><p>{turnCards[g.drawnCard??0].text}</p><button className="story-primary" onClick={()=>set(playTurnCard)}>Play on {turnCards[g.drawnCard??0].alex<0?'Alex’s Imperial House':'your operation'} →</button></div>}
 {stage==='cash'&&<div className="turn-panel"><h3>Allocate your cash</h3><p>{g.turnNote} Available: {cash(g.cash)}.</p><div className="turn-destinations"><button onClick={()=>set(x=>allocateTurnCash(x,'save'))}><b>Bank the cash</b><small>Keep your reserve for future opportunities.</small></button><button disabled={g.cash<150} onClick={()=>set(x=>allocateTurnCash(x,'train'))}><b>Train your team · $150</b><small>+$50 income every future night.</small></button><button disabled={g.cash<500||g.shops.includes('Jade Garden')} onClick={()=>set(x=>allocateTurnCash(x,'property'))}><b>Buy Jade Garden · $500</b><small>New placement option from next turn.</small></button></div></div>}
 {stage==='end'&&<div className="turn-panel"><h3>Your turn is complete</h3><p>{g.turnNote}</p><div className="story-lesson"><b>{b.choices[g.lastChoice??0].lesson}</b></div><button className="story-primary" onClick={()=>{pick(null);set(endTurn);}}>End turn · {g.beat===9?'see the finale':'Alex responds'} →</button></div>}
 {rain&&<div className="story-cash-rain" aria-hidden="true">{Array.from({length:24},(_,i)=><span key={i} style={{left:`${i*37%100}%`,animationDelay:`${i%6*.1}s`}}>💵</span>)}</div>}
 </section>;
}
