import { useRef } from 'react';
import { districts,hexDistance,parlours,shopStats,staff,type Monopoly } from './monopoly';
import { Portrait } from './Portrait';
const points=Array.from({length:6},(_,i)=>{const a=(30+i*60)*Math.PI/180;return`${Math.cos(a)*73},${Math.sin(a)*73}`;}).join(' ');
export function HexMap({game,focus,onFocus,onDropWorker,onSelectWorker,selected=null}:{game:Monopoly;focus:number|null;onFocus:(i:number)=>void;onDropWorker?:(worker:number,shop:number)=>void;onSelectWorker?:(i:number)=>void;selected?:number|null}){
 const touch=useRef<{worker:number;x:number;y:number}|null>(null);
 const pos=(i:number)=>({x:400+parlours[i].q*130+parlours[i].r*65,y:350+parlours[i].r*113});
 return <section className="mm-hex-city mm-honeycomb"><div className="mm-ownership-key"><strong>♛ YOU · LOTUS SYNDICATE</strong><strong>♜ ALEX · BLUE ORCHID</strong><strong>◇ FOR SALE</strong></div><div className="mm-district-strip">{districts.map(d=><div key={d.name} style={{borderColor:d.color}}><b>{d.symbol} {d.name}</b><small>{d.perk}</small></div>)}</div><div className="mm-hex-scroll"><svg viewBox="0 0 800 690" className="mm-hex-map" role="group" aria-label="Honeycomb nightlife district map. Drag your staff into your shops or select staff and inspect a hex.">
 <defs><clipPath id="hex-content-clip"><polygon points={points}/></clipPath><radialGradient id="hex-night"><stop stopColor="#3f273f"/><stop offset="1" stopColor="#101524"/></radialGradient><pattern id="city-dots" width="26" height="26" patternUnits="userSpaceOnUse"><circle cx="2" cy="2" r="1" fill="#ae83b9" opacity=".14"/></pattern></defs><rect width="800" height="690" rx="24" fill="url(#hex-night)"/><rect width="800" height="690" fill="url(#city-dots)"/>
 <text x="400" y="38" textAnchor="middle" fill="#e6bbcf" fontSize="15" letterSpacing="3">THE MONEY MILE</text><text x="400" y="59" textAnchor="middle" fill="#b59eaf" fontSize="10">GOOD GROUND. BAD NEIGHBOURS. YOUR NEXT MOVE.</text>
 {game.patrols.map((p,i)=>{const{x,y}=pos(p);return<circle key={`radius-${i}`} cx={x} cy={y} r="130" fill="#6382ef" fillOpacity=".035" stroke="#7c9be4" strokeOpacity=".3" strokeDasharray="5 6"/>;})}
 {parlours.map((p,i)=>{const{x,y}=pos(i),owner=game.shops[i],stats=shopStats(game,i),d=districts[p.district],closed=game.closed.includes(i),raided=game.raided.includes(i)&&game.phase==='reward';return<g key={p.name} transform={`translate(${x} ${y})`} role="button" tabIndex={0} data-shop={i} aria-pressed={focus===i} aria-label={`${p.name}, ${d.name}, ${owner==='you'?'your shop':owner==='alex'?'Alex’s shop':closed?'closed':'for sale'}, ${stats.team.length} staff`} className={`mm-hex-node ${raided?'raid-hit':''}`} onClick={()=>onFocus(i)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onFocus(i);}}} onDragOver={e=>{if(game.phase==='assign'&&owner==='you'){e.preventDefault();e.dataTransfer.dropEffect='move';}}} onDrop={e=>{e.preventDefault();const raw=e.dataTransfer.getData('application/x-mm-worker')||e.dataTransfer.getData('text/plain');if(/^\d+$/.test(raw)&&game.phase==='assign'&&owner==='you'){onFocus(i);onDropWorker?.(Number(raw),i);}}}>
 <polygon points={points} fill={closed?'#52252b':p.district===3?'#693038':p.district===2?'#2b5744':p.district===1?'#25505f':'#583657'} stroke={focus===i?'#fff1cb':d.color} strokeWidth={focus===i?3:1.5}/><polygon points={points} transform="scale(.94)" fill="none" stroke={owner==='you'?'#f6abc9':owner==='alex'?'#a0b5fa':'#d2b568'} strokeWidth={owner?5:1} opacity="1"/>
 <g clipPath="url(#hex-content-clip)">
 <text y="-55" textAnchor="middle" fontSize="15">{closed?'⛔':d.symbol}</text>
 <rect x="-48" y="-44" width="96" height="17" rx="5" fill={owner==='you'?'#f19ac0':owner==='alex'?'#8ba5f0':'#e2c477'}/>
 <text y="-32" textAnchor="middle" fill="#211723" fontSize="9" fontWeight="900">{owner==='you'?'♛ YOUR SHOP':owner==='alex'?'♜ ALEX’S SHOP':closed?'CLOSED / LOST':'◇ FOR SALE'}</text>
 <text y="-14" textAnchor="middle" fill="#fff4f7" fontSize="10" fontWeight="700"><tspan x="0">{p.name.split(' ').slice(0,-1).join(' ')}</tspan><tspan x="0" dy="12">{p.name.split(' ').at(-1)}</tspan></text>

 {stats.team.length===0?<><text y="19" textAnchor="middle" fill="#b9a9b9" fontSize="9">{closed?'Operation shut down':'2 empty rooms'}</text><text y="35" textAnchor="middle" fill="#aa99ad" fontSize="8">{game.phase==='assign'&&owner==='you'?'DROP STAFF HERE':'Inspect this hex'}</text></>:stats.team.map((worker,j)=><foreignObject key={worker} x={stats.team.length===1?-20:j===0?-45:5} y="4" width="40" height="50"><div className={`mm-room-worker ${selected===worker?'active':''}`} draggable={game.phase==='assign'&&owner==='you'} onClick={e=>{e.stopPropagation();onFocus(i);onSelectWorker?.(worker);}} onDragStart={e=>{e.stopPropagation();e.dataTransfer.setData('application/x-mm-worker',String(worker));e.dataTransfer.setData('text/plain',String(worker));e.dataTransfer.effectAllowed='move';onSelectWorker?.(worker);}} onPointerDown={e=>{if(e.pointerType!=='mouse'&&game.phase==='assign'&&owner==='you'){touch.current={worker,x:e.clientX,y:e.clientY};e.currentTarget.setPointerCapture(e.pointerId);}}} onPointerUp={e=>{const start=touch.current;touch.current=null;if(start&&Math.hypot(e.clientX-start.x,e.clientY-start.y)>12){const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-shop]');const shop=target?.getAttribute('data-shop');if(shop!==null&&shop!==undefined)onDropWorker?.(start.worker,Number(shop));}}}><Portrait index={worker} name={staff[worker].name} small/><span>{staff[worker].name}</span></div></foreignObject>)}
 {game.phase==='reward'&&game.raidEvents.filter(e=>e.shop===i&&e.worker!==null).map(e=><foreignObject key={`lost-${e.worker}`} x="-24" y="-6" width="48" height="65"><div className="mm-lost-worker"><Portrait index={e.worker!} name={staff[e.worker!].name} small/><b>✕ LOST</b></div></foreignObject>)}
 <text y="61" textAnchor="middle" fill="#fff0ed" fontSize="7.5" fontWeight="700">{closed?'LOST':p.district===2?'SAFE · PREMIUM':p.district===3?'DANGER · HIGH CASH':p.district===0?'TACTICAL · PARTY':'TOURIST · DEMAND'}</text>{raided&&<text x="40" y="-31" fontSize="19">🚨</text>}
 </g>
 {selected!==null&&game.assignments[selected]!==null&&game.phase==='assign'&&hexDistance(game.assignments[selected]!,i)===1&&<polygon points={points} transform="scale(.86)" fill="none" stroke="#fff0bd" strokeWidth="1.5" strokeDasharray="4 4" pointerEvents="none"/>}

 </g>;})}
 {game.patrols.map((p,i)=>{const{x,y}=pos(p);return<g key={`patrol-${i}`} transform={`translate(${x+46} ${y-49})`} role="img" aria-label={`Police patrol at ${parlours[p].name}`}><circle r="16" fill="#19233c" stroke="#92aaf6" strokeWidth="2"/><text y="5" textAnchor="middle" fontSize="18">🚔</text></g>;})}
 </svg></div><div className="mm-map-legend"><span>Pink rim: you</span><span>Blue rim: Alex</span><span>Gold rim: for sale</span><span>💎 Safe premium · ⚠ Risky cash · 🚔 Patrol pressure</span></div></section>;
}
