import { CARDS } from '@/content/cards';
import { MAMASAN_BY_ID } from '@/content/mamasans';
export type Side='you'|'alex';
const profiles=[
 {id:'anong',age:34,ethnicity:'Thai',price:450,income:165,attractiveness:3,friendliness:5,aggression:2,sneakiness:2,tagline:'THE TEAM ANCHOR',strength:'Warmth makes a shared room profitable.',weakness:'Needs a teammate to reach her earning potential.'},
 {id:'mali',age:29,ethnicity:'Chinese',price:700,income:205,attractiveness:4,friendliness:2,aggression:5,sneakiness:4,tagline:'THE FEARLESS HUSTLER',strength:'Party-district demand and bold earnings.',weakness:'Maximum aggression attracts police.'},
 {id:'dao',age:30,ethnicity:'Japanese',price:650,income:190,attractiveness:4,friendliness:1,aggression:3,sneakiness:5,tagline:'THE SILENT SCHEMER',strength:'Best at dodging patrol attention.',weakness:'Poor teamwork; prefers her own room.'},
 {id:'nok',age:24,ethnicity:'Filipino',price:1800,income:480,attractiveness:5,friendliness:4,aggression:1,sneakiness:2,tagline:'THE ALL-IN SUPERSTAR',strength:'Huge booking power and strong chemistry.',weakness:'Takes your entire draft budget. Expensive retainer.'},
 {id:'pim',age:39,ethnicity:'Korean',price:400,income:150,attractiveness:2,friendliness:2,aggression:4,sneakiness:3,tagline:'THE HARD-NOSED VETERAN',strength:'Affordable party-quarter specialist.',weakness:'Confrontational; police losses can be steep.'},
 {id:'lek',age:32,ethnicity:'Indian',price:550,income:180,attractiveness:3,friendliness:4,aggression:2,sneakiness:1,tagline:'THE HONEST HEART',strength:'Makes friends and keeps regulars returning.',weakness:'Cannot hide activity from police.'},
 {id:'kanya',age:26,ethnicity:'Thai',price:950,income:265,attractiveness:5,friendliness:3,aggression:4,sneakiness:3,tagline:'THE NEON HEADLINER',strength:'High earnings and strong party demand.',weakness:'Costly hire with meaningful enforcement risk.'},
 {id:'suda',age:43,ethnicity:'Chinese',price:350,income:145,attractiveness:1,friendliness:4,aggression:2,sneakiness:4,tagline:'THE QUIET FIXER',strength:'Cheap, sociable and discreet.',weakness:'Lowest attraction; relies on regular clients.'},
 {id:'araya',age:23,ethnicity:'Japanese',price:500,income:180,attractiveness:4,friendliness:3,aggression:4,sneakiness:3,tagline:'THE REBEL ROOKIE',strength:'Affordable appetite for busy nights.',weakness:'Aggressive decisions put her shop at risk.'},
 {id:'chaba',age:34,ethnicity:'Filipino',price:800,income:225,attractiveness:4,friendliness:2,aggression:3,sneakiness:4,tagline:'THE POLISHED OPERATOR',strength:'Good bookings with a discreet edge.',weakness:'Limited teamwork and an expensive contract.'},
 {id:'nida',age:28,ethnicity:'Korean',price:600,income:190,attractiveness:2,friendliness:3,aggression:3,sneakiness:3,tagline:'THE BALANCED TACTICIAN',strength:'Flexible across districts; learns cheaply.',weakness:'No dominant trait; modest walk-in demand.'},
 {id:'siriporn',age:45,ethnicity:'Indian',price:900,income:245,attractiveness:3,friendliness:3,aggression:3,sneakiness:2,tagline:'THE SEASONED CAPTAIN',strength:'Strong base earnings without extreme aggression.',weakness:'High price and weaker discretion.'},
];
export const staff=profiles.map((p,i)=>({...p,name:MAMASAN_BY_ID[p.id].name,friend:i%2===0?i+1:i-1}));
export const districts=[
 {name:'Party Quarter',symbol:'🔥',perk:'Aggression boosts cash and busy-night odds. High police exposure.',color:'#d98abb',upkeep:50,risk:.07},
 {name:'Waterfront',symbol:'🌊',perk:'Attractiveness drives walk-ins. Busy nights pay 50% extra.',color:'#75cddb',upkeep:65,risk:.025},
 {name:'Uptown Sanctuary',symbol:'💎',perk:'+$60 premium per therapist. Friendliness earns reliable bookings.',color:'#a8d497',upkeep:80,risk:0},
 {name:'Red-Light Backstreets',symbol:'⚠',perk:'+25% base cash and cheap upkeep. Highest risk of seizure.',color:'#e88275',upkeep:30,risk:.12},
];
const names=['Golden Lotus','Temple Street','Moonlight Garden','Lucky Star','Blue Orchid','Harbour Rooms','Riverside Lounge','Embassy Rooms','Velvet Room','Diamond House','Grand Palace','Imperial Spa','Rose Rooms','Lantern House','Lotus Court','Jade Garden','Orchid Lane','Silk Rooms','Midnight Spa'];
const coords:Array<{q:number;r:number}>=[];for(let r=-2;r<=2;r++)for(let q=-2;q<=2;q++)if(Math.abs(q+r)<=2)coords.push({q,r});
export const parlours=coords.map(({q,r},i)=>{const distance=Math.max(Math.abs(q),Math.abs(r),Math.abs(q+r)),district=distance<=1?2:q<=-1?3:r>=1?1:0;return{name:names[i],q,r,district,price:1000,capacity:2};});
export type Phase='pick'|'reveal'|'assign'|'spin'|'reward'|'draw'|'invest'|'computer'|'over';
export type RaidEvent={side:Side;shop:number;worker:number|null;seized:boolean};
export type Monopoly={version:4;round:number;phase:Phase;cash:Record<Side,number>;workers:(Side|null)[];shops:(Side|null)[];assignments:(number|null)[];levels:number[];die:number|null;market:number;reward:Record<Side,number>;gross:Record<Side,number>;costs:Record<Side,number>;card:number|null;cardPlayed:boolean;police:boolean;raided:number[];raidEvents:RaidEvent[];unavailable:number[];closed:number[];losses:Record<Side,number>;bonus:Record<Side,number>;boost:Record<Side,number>;shield:Record<Side,boolean>;discount:Record<Side,number>;hireDiscount:Record<Side,number>;trainingDiscount:Record<Side,number>;heat:number[];blocked:Record<Side,boolean>;hires:Record<Side,number>;moves:Record<Side,number>;patrols:number[];computerStep:number;computerCard:number|null;draftTurn:Side;draftDone:Record<Side,boolean>;log:string[];tacticsUsed:number;promotions:number[]};
export function newMonopoly(seed=Math.random()):Monopoly{let value=Math.floor(seed*2147483646)+1;const random=()=>{value=value*16807%2147483647;return value/2147483647;};const order=parlours.map((_,i)=>i);for(let i=order.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[order[i],order[j]]=[order[j],order[i]];}return{version:4,round:1,phase:'pick',cash:{you:1800,alex:1800},workers:staff.map(()=>null),shops:parlours.map((_,i)=>order.slice(0,3).includes(i)?'you':order.slice(3,6).includes(i)?'alex':null),assignments:staff.map(()=>null),levels:staff.map(()=>0),die:null,market:.5,reward:{you:0,alex:0},gross:{you:0,alex:0},costs:{you:0,alex:0},card:null,cardPlayed:false,police:false,raided:[],raidEvents:[],unavailable:[],closed:[],losses:{you:0,alex:0},bonus:{you:0,alex:0},boost:{you:0,alex:0},shield:{you:false,alex:false},discount:{you:0,alex:0},hireDiscount:{you:0,alex:0},trainingDiscount:{you:0,alex:0},heat:parlours.map(()=>0),blocked:{you:false,alex:false},hires:{you:0,alex:0},moves:{you:0,alex:0},patrols:[0,18],computerStep:0,computerCard:null,draftTurn:'you',draftDone:{you:false,alex:false},tacticsUsed:0,promotions:parlours.map(()=>0),log:['Captain’s draft: $1,800 each. Alternate picks. Up to three staff, or one expensive star. The map stays hidden until both teams lock in.']};}
const copy=(g:Monopoly):Monopoly=>({...g,cash:{...g.cash},workers:[...g.workers],shops:[...g.shops],assignments:[...g.assignments],levels:[...g.levels],reward:{...g.reward},gross:{...g.gross},costs:{...g.costs},losses:{...g.losses},bonus:{...g.bonus},boost:{...g.boost},shield:{...g.shield},discount:{...g.discount},hireDiscount:{...g.hireDiscount},trainingDiscount:{...g.trainingDiscount},hires:{...g.hires},moves:{...g.moves},patrols:[...g.patrols],raided:[...g.raided],raidEvents:[...g.raidEvents],unavailable:[...g.unavailable],closed:[...g.closed],heat:[...g.heat],blocked:{...g.blocked},draftDone:{...g.draftDone},promotions:[...g.promotions],log:[...g.log]});
const other=(who:Side):Side=>who==='you'?'alex':'you';
export const team=(g:Monopoly,who:Side)=>g.workers.flatMap((w,i)=>w===who?[i]:[]);
export const score=(g:Monopoly,who:Side)=>g.cash[who]+g.shops.reduce((s,o,i)=>s+(o===who?parlours[i].price:0),0)+team(g,who).reduce((s,i)=>s+staff[i].price+g.levels[i]*200,0);
export const roomCount=(g:Monopoly,who:Side)=>g.shops.reduce((s,o,i)=>s+(o===who?parlours[i].capacity:0),0);
export const staffCost=(i:number)=>Math.round(20+staff[i].price*.045);
export const nightlyCosts=(g:Monopoly,who:Side)=>g.shops.reduce((s,o,i)=>s+(o===who?districts[parlours[i].district].upkeep:0),0)+team(g,who).reduce((s,i)=>s+staffCost(i),0);
function advanceDraft(n:Monopoly,who:Side){for(const side of ['you','alex'] as const){if(team(n,side).length>=3||!staff.some((b,i)=>!n.workers[i]&&b.price<=n.cash[side]))n.draftDone[side]=true;}const rival=other(who);if(n.draftDone.you&&n.draftDone.alex){n.phase='reveal';return;}n.draftTurn=n.draftDone[rival]?who:rival;}
function draftPick(g:Monopoly,who:Side,i:number){if(g.phase!=='pick'||g.draftTurn!==who||g.draftDone[who]||!staff[i]||g.workers[i]||g.cash[who]<staff[i].price||team(g,who).length>=3)return g;const n=copy(g);n.workers[i]=who;n.cash[who]-=staff[i].price;n.log.push(`${who==='you'?'You':'Alex'} drafted ${staff[i].name} (${staff[i].tagline}) for $${staff[i].price}.`);advanceDraft(n,who);return n;}
export const pick=(g:Monopoly,i:number)=>draftPick(g,'you',i);
export function passDraft(g:Monopoly){if(g.phase!=='pick'||g.draftTurn!=='you'||team(g,'you').length===0)return g;const n=copy(g);n.draftDone.you=true;advanceDraft(n,'you');return n;}
export function alexDraft(g:Monopoly){if(g.phase!=='pick'||g.draftTurn!=='alex')return g;const count=team(g,'alex').length,slots=3-count;const options=staff.map((b,i)=>({b,i})).filter(({b,i})=>!g.workers[i]&&b.price<=g.cash.alex);if(!options.length){const n=copy(g);n.draftDone.alex=true;advanceDraft(n,'alex');return n;}const sorted=options.sort((a,b)=>{const value=(x:typeof a)=>((x.b.income+x.b.attractiveness*10+x.b.friendliness*8)/(x.b.price+staffCost(x.i)*8))*(x.b.price<=g.cash.alex/slots?1.4:1);return value(b)-value(a);});return draftPick(g,'alex',sorted[0].i);}
export function assign(g:Monopoly,worker:number,shop:number|null):Monopoly{if(g.phase!=='assign'||g.workers[worker]!=='you')return g;if(shop!==null&&(!parlours[shop]||g.shops[shop]!=='you'||g.assignments.filter((s,i)=>s===shop&&i!==worker).length>=2))return g;const n=copy(g);n.assignments[worker]=shop;return n;}
export function hexDistance(a:number,b:number){const x=parlours[a],y=parlours[b];return(Math.abs(x.q-y.q)+Math.abs(x.r-y.r)+Math.abs(x.q+x.r-y.q-y.r))/2;}
export function shopStats(g:Monopoly,shop:number){const who=g.shops[shop],members=g.workers.flatMap((w,i)=>who&&w===who&&g.assignments[i]===shop?[i]:[]),p=parlours[shop];const avg=(key:'aggression'|'friendliness'|'attractiveness'|'sneakiness')=>members.length?members.reduce((s,i)=>s+staff[i][key],0)/members.length:0;const proximity=Math.min(...g.patrols.map(i=>hexDistance(i,shop))),pressure=proximity===0?.08:proximity===1?.04:0;const risk=Math.min(.5,Math.max(.03,.07+districts[p.district].risk+avg('aggression')*.023-avg('friendliness')*.008-avg('sneakiness')*.013+pressure+g.heat[shop]*.04));const busy=Math.min(.5,.25+(p.district===0?avg('aggression')*.04:p.district===1?avg('attractiveness')*.025:0));return{team:members,risk:members.length?risk:0,busy,pressure,proximity};}
export function workerPay(g:Monopoly,i:number,market:number){const s=g.assignments[i],who=g.workers[i];if(s===null||!who||g.shops[s]!==who)return 0;const b=staff[i],p=parlours[s],stats=shopStats(g,s),mates=stats.team.length-1;let base=b.income+g.levels[i]*65+b.attractiveness*12+(p.district===2?60:0)+mates*b.friendliness*15;if(p.district===0)base*=1+b.aggression*.075;if(p.district===3)base*=1.25;if(g.assignments[b.friend]===s&&g.workers[b.friend]===who)base+=50;const quiet=.4+b.friendliness*.1;let mult=market<.2?quiet:market>=1-stats.busy?1.6:1;if(p.district===1&&market>=1-stats.busy)mult*=1.5;const control=g.shops.filter((o,j)=>o===who&&parlours[j].district===p.district).length>=3?1.1:1;return Math.round(base*mult*control*(1+g.boost[who]+g.promotions[s]));}
export const income=(g:Monopoly,i:number,die:number)=>workerPay(g,i,(die-.5)/6);
export function forecast(g:Monopoly,who:Side){let gross=0,loss=0;for(const i of team(g,who)){if(g.assignments[i]===null)continue;const stats=shopStats(g,g.assignments[i]!);const pay=workerPay(g,i,.1)*.2+workerPay(g,i,.5)*(1-.2-stats.busy)+workerPay(g,i,.99)*stats.busy;gross+=pay;loss+=g.shield[who]?0:pay*stats.risk*(.25+staff[i].aggression*.04);}const costs=nightlyCosts(g,who);return{gross:Math.round(gross),riskCost:Math.round(loss),costs,net:Math.round(gross-loss)-costs};}
function placeOne(g:Monopoly,i:number){const options=g.shops.flatMap((o,s)=>o==='alex'&&g.assignments.filter((x,j)=>x===s&&j!==i).length<2?[s]:[]);let best:number|null=null,value=-Infinity;for(const s of options){g.assignments[i]=s;const f=forecast(g,'alex');if(f.net>value){value=f.net;best=s;}}g.assignments[i]=best;return best;}
function loseShop(n:Monopoly,shop:number){n.shops[shop]=null;n.closed.push(shop);n.assignments=n.assignments.map(s=>s===shop?null:s);}
export function spin(g:Monopoly,die:number,policeRoll=.5,market=(die-.5)/6):Monopoly{if(g.phase!=='spin'||!Number.isInteger(die)||die<1||die>6||policeRoll<0||policeRoll>=1||market<0||market>=1)return g;const n=copy(g);n.die=die;n.market=market;n.gross={you:0,alex:0};n.losses={you:0,alex:0};n.raided=[];n.raidEvents=[];n.closed=[];n.unavailable=[];n.shops.forEach((o,s)=>{if(o&&shopStats(n,s).team.length&&(n.round===2||policeRoll<shopStats(n,s).risk))n.raided.push(s);});n.police=n.raided.length>0;n.costs={you:nightlyCosts(n,'you'),alex:nightlyCosts(n,'alex')};n.workers.forEach((who,i)=>{if(!who)return;const gross=workerPay(n,i,market);const loss=n.assignments[i]!==null&&n.raided.includes(n.assignments[i]!)&&!n.shield[who]?Math.round(gross*(.25+staff[i].aggression*.04)):0;n.gross[who]+=gross;n.losses[who]+=loss;});
 // One consequential asset loss per side, with at least one owned shop surviving.
 for(const who of ['you','alex'] as const){const targets=n.raided.filter(s=>n.shops[s]===who);if(targets.length&&!n.shield[who]){const shop=targets.sort((a,b)=>shopStats(n,b).risk-shopStats(n,a).risk)[0];const members=shopStats(n,shop).team.sort((a,b)=>staff[b].aggression-staff[a].aggression);const worker=members[0]??null;const seized=parlours[shop].district===3&&n.shops.filter(o=>o===who).length>1;if(seized)loseShop(n,shop);else if(worker!==null){n.workers[worker]=null;n.assignments[worker]=null;n.unavailable.push(worker);}n.raidEvents.push({side:who,shop,worker:seized?null:worker,seized});n.log.push(`${who==='you'?'Your':'Alex’s'} ${seized?'property '+parlours[shop].name+' was seized':staff[worker!].name+' lost her contract during the inspection'}.`);}if(!targets.length||n.shield[who])n.gross[who]+=n.bonus[who];n.reward[who]=n.gross[who]-n.losses[who]-n.costs[who];n.cash[who]=Math.max(0,n.cash[who]+n.reward[who]);}
 n.promotions=parlours.map(()=>0);n.boost={you:0,alex:0};n.bonus={you:0,alex:0};n.shield={you:false,alex:false};n.heat=n.heat.map(h=>Math.max(0,h-1));n.phase='reward';n.card=null;n.cardPlayed=false;n.log.push(`Night ${n.round}: you netted $${n.reward.you}; Alex netted $${n.reward.alex}.`);return n;}
const definitions=[
 {id:'cash_buyer',text:'Property purchases cost $350 less this round. Build before Alex claims the good hexes.',effect:'discount',target:'none'},
 {id:'recruitment_drive',text:'Your one new hire costs $250 less this round. Race Alex for the remaining talent.',effect:'hireDiscount',target:'none'},
 {id:'renovation_grant',text:'Training costs $100 less this round. Each training adds $65 nightly bookings.',effect:'training',target:'none'},
 {id:'bad_review',text:'Target an Alex parlour: deduct $250 for cancelled bookings and block Alex’s next recruitment.',effect:'block',target:'rivalShop'},
 {id:'anonymous_tip',text:'Move a patrol onto an Alex parlour now and add 2 Heat. His next placement will react to the risk.',effect:'heat',target:'rivalShop'},
 {id:'licence_challenge',text:'Close an Alex parlour immediately, evicting its staff. Cannot remove his final parlour.',effect:'close',target:'rivalShop'},
 {id:'better_offer',text:'Offer a contract to one Alex therapist. If you have room, she switches teams immediately. Uses your one hire.',effect:'poach',target:'rivalWorker'},
 {id:'high_roller',text:'Receive $300 for bookings now. Spend it on training, hiring or territory.',effect:'cash',target:'none'},
 {id:'tip_off',text:'Your staff and parlours are protected from police losses and seizures next night.',effect:'shield',target:'none'},
 {id:'insurance_payout',text:'Recover up to $400 of police cash losses and restore your most recent lost contract or parlour if still available.',effect:'restore',target:'none'},
 {id:'property_boom',text:'Receive $200, but add 1 Heat to all your staffed shops. Cash now creates police risk next night.',effect:'cashHeat',target:'none'},
 {id:'monsoon',text:'Both teams lose up to $200 now. Budget carefully; Alex immediately has less cash to invest.',effect:'bothLoss',target:'none'},
] as const;
export const cards=definitions.map(c=>({...c,title:CARDS.find(d=>d.id===c.id)!.name,category:CARDS.find(d=>d.id===c.id)!.category,flavour:CARDS.find(d=>d.id===c.id)!.flavour}));
export function drawCard(g:Monopoly,index:number){if(g.phase!=='draw'||!cards[index])return g;return{...g,phase:'invest' as const,card:index,cardPlayed:false};}
export function cardTargets(g:Monopoly,index:number,who:Side='you'){const c=cards[index],rival=other(who);if(c.target==='rivalShop')return g.shops.flatMap((o,i)=>o===rival&&(c.effect!=='close'||g.shops.filter(s=>s===rival).length>1)?[i]:[]);if(c.target==='rivalWorker')return team(g,rival);return[];}
function applyCard(n:Monopoly,index:number,who:Side,target:number|null){const c=cards[index],rival=other(who);if(c.target!=='none'&&!cardTargets(n,index,who).includes(target!))return false;switch(c.effect){case'discount':n.discount[who]=350;break;case'hireDiscount':n.hireDiscount[who]=250;break;case'training':n.trainingDiscount[who]=100;break;case'block':n.cash[rival]=Math.max(0,n.cash[rival]-250);n.blocked[rival]=true;break;case'heat':n.heat[target!]+=2;n.patrols[0]=target!;break;case'close':loseShop(n,target!);break;case'poach':if(recruitReason(n,who))return false;n.workers[target!]=who;n.assignments[target!]=null;n.hires[who]++;break;case'cash':n.cash[who]+=300;break;case'shield':n.shield[who]=true;break;case'restore':{n.cash[who]+=Math.min(400,n.losses[who]);const event=n.raidEvents.find(e=>e.side===who);if(event?.seized&&n.shops[event.shop]===null){n.shops[event.shop]=who;n.closed=n.closed.filter(s=>s!==event.shop);}else if(event?.worker!==null&&event?.worker!==undefined&&!n.workers[event.worker]&&team(n,who).length<roomCount(n,who)){n.workers[event.worker]=who;n.unavailable=n.unavailable.filter(i=>i!==event.worker);}break;}case'cashHeat':n.cash[who]+=200;n.shops.forEach((o,s)=>{if(o===who&&shopStats(n,s).team.length)n.heat[s]++;});break;case'bothLoss':n.cash.you=Math.max(0,n.cash.you-200);n.cash.alex=Math.max(0,n.cash.alex-200);break;}n.log.push(`${who==='you'?'You':'Alex'} played ${c.title}${target!==null?' on '+(c.target==='rivalWorker'?staff[target].name:parlours[target].name):''}. ${c.text}`);return true;}
export function playCard(g:Monopoly,target:number|null=null){if(g.phase!=='invest'||g.card===null||g.cardPlayed)return g;const n=copy(g);if(!applyCard(n,n.card!,'you',target))return g;n.cardPlayed=true;return n;}
export function discardCard(g:Monopoly){if(g.phase!=='invest'||g.cardPlayed)return g;const n=copy(g);n.cardPlayed=true;n.log.push('You discarded the strategy card instead of playing it.');return n;}
export const propertyCost=(g:Monopoly,i:number,who:Side='you')=>Math.max(100,parlours[i].price-g.discount[who]);
export const hiringCost=(g:Monopoly,i:number,who:Side='you')=>Math.max(100,staff[i].price-g.hireDiscount[who]);
export const trainingCost=(g:Monopoly,i:number,who:Side='you')=>Math.max(50,(staff[i].id==='nida'?150:250)-g.trainingDiscount[who]);
export function recruitReason(g:Monopoly,who:Side='you'){if(g.moves[who]>=2)return'Two investments used';if(g.hires[who]>=1)return'One recruitment per round';if(g.blocked[who])return'Recruitment blocked by Bad Review';if(team(g,who).length>=roomCount(g,who))return'No room — expand first';return null;}
function buy(n:Monopoly,kind:'worker'|'shop'|'train'|'sell',i:number,who:Side){if(n.moves[who]>=2)return false;if(kind==='worker'){if(!staff[i]||n.workers[i]||n.unavailable.includes(i)||recruitReason(n,who)||n.cash[who]<hiringCost(n,i,who))return false;n.cash[who]-=hiringCost(n,i,who);n.workers[i]=who;n.hires[who]++;}else if(kind==='train'){if(n.workers[i]!==who||n.levels[i]>=2||n.cash[who]<trainingCost(n,i,who))return false;n.cash[who]-=trainingCost(n,i,who);n.levels[i]++;}else if(kind==='sell'){if(n.shops[i]!==who||n.shops.filter(s=>s===who).length<=1)return false;n.cash[who]+=850;loseShop(n,i);}else{if(!parlours[i]||n.shops[i]||n.closed.includes(i)||n.cash[who]<propertyCost(n,i,who))return false;n.cash[who]-=propertyCost(n,i,who);n.shops[i]=who;}n.moves[who]++;n.log.push(`${who==='you'?'You':'Alex'} ${kind==='worker'?'hired '+staff[i].name:kind==='train'?'trained '+staff[i].name:kind==='sell'?'sold '+parlours[i].name:'bought '+parlours[i].name}.`);return true;}
export function invest(g:Monopoly,kind:'worker'|'shop'|'train'|'sell',i:number){if(g.phase!=='invest')return g;const n=copy(g);return buy(n,kind,i,'you')?n:g;}
export function endRound(g:Monopoly){if(g.phase!=='invest'||!g.cardPlayed)return g;return{...g,phase:'computer' as const,computerStep:0,computerCard:null,tacticsUsed:0};}
export function computerAction(g:Monopoly,cardIndex=0){if(g.phase!=='computer')return g;const n=copy(g);if(n.computerStep===0){if(!cards[cardIndex])return g;n.computerCard=cardIndex;const target=cardTargets(n,cardIndex,'alex')[0]??null;if(!applyCard(n,cardIndex,'alex',target))n.log.push(`Alex discards ${cards[cardIndex].title}: no legal target.`);n.computerStep++;return n;}
 if(n.computerStep===1){const options=staff.map((b,i)=>({b,i})).filter(({i})=>!n.workers[i]&&!n.unavailable.includes(i)&&hiringCost(n,i,'alex')<=n.cash.alex).sort((a,b)=>(b.b.income+b.b.attractiveness*12)/hiringCost(n,b.i,'alex')-(a.b.income+a.b.attractiveness*12)/hiringCost(n,a.i,'alex'));if(!recruitReason(n,'alex')&&options[0])buy(n,'worker',options[0].i,'alex');else{const trainee=team(n,'alex').find(i=>n.levels[i]<2&&trainingCost(n,i,'alex')<=n.cash.alex);if(trainee!==undefined)buy(n,'train',trainee,'alex');else n.log.push('Alex cannot recruit or train within the current budget and card constraints.');}n.computerStep++;return n;}
 if(n.computerStep===2){const options=parlours.map((p,i)=>({p,i})).filter(({i})=>!n.shops[i]&&!n.closed.includes(i)&&propertyCost(n,i,'alex')<=n.cash.alex).sort((a,b)=>districts[a.p.district].risk-districts[b.p.district].risk);if(options[0]&&n.cash.alex-propertyCost(n,options[0].i,'alex')>=nightlyCosts(n,'alex'))buy(n,'shop',options[0].i,'alex');else{const trainee=team(n,'alex').find(i=>n.levels[i]<2&&trainingCost(n,i,'alex')<=n.cash.alex);if(trainee!==undefined)buy(n,'train',trainee,'alex');else n.log.push('Alex saves cash rather than expanding beyond a safe reserve.');}n.workers.forEach((w,i)=>{if(w==='alex')n.assignments[i]=null;});n.computerStep++;return n;}
 const members=team(n,'alex'),i=members[n.computerStep-3];if(i!==undefined){const s=placeOne(n,i);n.log.push(s===null?`Alex rests ${staff[i].name}: no rooms available.`:`Alex matches ${staff[i].name} to ${parlours[s].name}. Expected team net $${forecast(n,'alex').net}; police risk ${Math.round(shopStats(n,s).risk*100)}%.`);n.computerStep++;return n;}
 if(n.tacticsUsed<2){for(const worker of team(n,'alex')){if(n.assignments[worker]===null)continue;const target=parlours.findIndex((_,s)=>n.shops[s]==='you'&&tacticQuote(n,worker,s,'pressure','alex').legal);if(target>=0)return tacticalMove(n,worker,target,'pressure','alex');}n.tacticsUsed=2;}
 const hot=parlours.map((_,i)=>({i,risk:shopStats(n,i).risk})).sort((a,b)=>b.risk-a.risk)[0].i,patrol=n.round%2;const options=parlours.flatMap((_,i)=>hexDistance(n.patrols[patrol],i)<=1?[i]:[]).sort((a,b)=>hexDistance(a,hot)-hexDistance(b,hot));n.patrols[patrol]=options[0];n.log.push(`Patrol moves to ${parlours[options[0]].name}, toward high-risk operations.`);n.phase=n.round===10?'over':'assign';if(n.phase!=='over')n.round++;n.tacticsUsed=0;n.moves={you:0,alex:0};n.hires={you:0,alex:0};n.discount={you:0,alex:0};n.hireDiscount={you:0,alex:0};n.trainingDiscount={you:0,alex:0};n.blocked={you:false,alex:false};n.closed=[];n.unavailable=[];return n;}
export function nextPhase(g:Monopoly){if(g.phase==='reveal'){const n=copy(g);for(const i of team(n,'alex'))placeOne(n,i);n.phase='assign';return n;}if(g.phase==='assign'&&team(g,'you').length===0){return{...g,phase:'spin' as const};}if(g.phase==='assign'&&team(g,'you').some(i=>g.assignments[i]!==null))return{...g,phase:'spin' as const};if(g.phase==='reward')return{...g,phase:'draw' as const};return g;}

export type TacticalMove='promote'|'pressure'|'lure'|'claim';
export function tacticQuote(g:Monopoly,worker:number,target:number,move:TacticalMove,who:Side='you'){
 const from=g.assignments[worker],b=staff[worker];
 if(!b||g.phase!=='assign'||g.workers[worker]!=='you'||from===null||!parlours[target])return{legal:false,cost:0,text:'Place your therapist in a shop first.'};
 if((g.tacticsUsed??0)>=2)return{legal:false,cost:0,text:'Two tactical orders already used this night.'};
 const distance=hexDistance(from,target);const rival=other(who);
 if(move==='promote'){const cost=80;if(g.shops[target]!==who||distance>1)return{legal:false,cost,text:'Promote from your shop or an adjacent owned shop.'};return{legal:g.cash[who]>=cost,cost,text:`+25% bookings at ${parlours[target].name} this night; +1 Heat. Spend $80 to push demand, accepting police risk.`};}
 if(move==='pressure'){const cost=50;if(g.shops[target]!==rival||distance!==1)return{legal:false,cost,text:'Pressure requires an adjacent Alex shop.'};const damage=b.aggression*45;return{legal:g.cash[who]>=cost,cost,text:`Alex loses up to $${damage} cash now; you gain +1 Heat at your base. Your aggression dictates the pressure.`};}
 if(move==='lure'){if(distance!==1)return{legal:false,cost:0,text:'Choose a hex adjacent to this staff member.'};return{legal:true,cost:0,text:`Move the nearest patrol to ${parlours[target].name}; reduce 1 Heat at your base. Choose a destination that protects your shops or exposes Alex.`};}
 const cost=Math.max(500,1000-b.friendliness*70);if(g.shops[target]||g.closed.includes(target)||distance!==1)return{legal:false,cost,text:'Claim requires an adjacent vacant, open shop.'};return{legal:g.cash[who]>=cost,cost,text:`Claim this adjacent property for $${cost} using ${b.name}’s connections. Two rooms and recurring upkeep; $${1000-cost} less than a distant purchase.`};
}
export function tacticalMove(g:Monopoly,worker:number,target:number,move:TacticalMove,who:Side='you'){const quote=tacticQuote(g,worker,target,move,who);if(!quote.legal)return g;const n=copy(g),from=n.assignments[worker]!;n.cash[who]-=quote.cost;n.tacticsUsed++;if(move==='promote'){n.promotions[target]+=.25;n.heat[target]++;}if(move==='pressure'){n.cash[other(who)]=Math.max(0,n.cash[other(who)]-staff[worker].aggression*45);n.heat[from]++;}if(move==='lure'){const patrol=n.patrols.map((s,i)=>({i,d:hexDistance(s,from)})).sort((a,b)=>a.d-b.d)[0].i;n.patrols[patrol]=target;n.heat[from]=Math.max(0,n.heat[from]-1);}if(move==='claim')n.shops[target]=who;n.log.push(`${staff[worker].name}: ${move.toUpperCase()} at ${parlours[target].name}. ${quote.text}`);return n;}
